/**
 * The window.gitTree bridge contract (ADR-0008, D6).
 * Generated from src/preload.js exposed API and kept in lockstep by
 * test/preload-contract.test.js. Invoke methods return Promise<unknown>
 * until their domain payloads are typed at the IPC seam (M4+); subscription
 * methods (on*) return an unsubscribe function.
 */
export interface GitTreeBridge {
  readonly platform: NodeJS.Platform;
  minimizeWindow(...args: unknown[]): Promise<unknown>;
  toggleMaximizeWindow(...args: unknown[]): Promise<unknown>;
  getWindowState(...args: unknown[]): Promise<unknown>;
  onWindowState(callback: (payload: unknown) => void): () => void;
  closeWindow(...args: unknown[]): Promise<unknown>;
  setTheme(...args: unknown[]): Promise<unknown>;
  getUpdateState(...args: unknown[]): Promise<unknown>;
  checkForUpdates(...args: unknown[]): Promise<unknown>;
  downloadUpdate(...args: unknown[]): Promise<unknown>;
  installUpdate(...args: unknown[]): Promise<unknown>;
  onUpdateState(callback: (payload: unknown) => void): () => void;
  onStaleInstall(callback: (payload: unknown) => void): () => void;
  getLog(...args: unknown[]): Promise<unknown>;
  getGraphPage(...args: unknown[]): Promise<unknown>;
  getDiff(...args: unknown[]): Promise<unknown>;
  getCommitDetail(...args: unknown[]): Promise<unknown>;
  getBranches(...args: unknown[]): Promise<unknown>;
  getBranchMetadata(...args: unknown[]): Promise<unknown>;
  compareBranches(...args: unknown[]): Promise<unknown>;
  compareCommits(...args: unknown[]): Promise<unknown>;
  getCommitFileDiff(...args: unknown[]): Promise<unknown>;
  checkoutBranch(...args: unknown[]): Promise<unknown>;
  checkoutTrackingBranch(...args: unknown[]): Promise<unknown>;
  createBranch(...args: unknown[]): Promise<unknown>;
  merge(...args: unknown[]): Promise<unknown>;
  renameBranch(...args: unknown[]): Promise<unknown>;
  rebaseBranch(...args: unknown[]): Promise<unknown>;
  trackBranch(...args: unknown[]): Promise<unknown>;
  fetchBranch(...args: unknown[]): Promise<unknown>;
  deleteRemoteBranch(...args: unknown[]): Promise<unknown>;
  deleteBranch(...args: unknown[]): Promise<unknown>;
  batchDeleteBranches(...args: unknown[]): Promise<unknown>;
  push(...args: unknown[]): Promise<unknown>;
  pull(...args: unknown[]): Promise<unknown>;
  fetch(...args: unknown[]): Promise<unknown>;
  getStatus(...args: unknown[]): Promise<unknown>;
  getWorkingTree(...args: unknown[]): Promise<unknown>;
  getWorkingDiff(...args: unknown[]): Promise<unknown>;
  stagePaths(...args: unknown[]): Promise<unknown>;
  unstagePaths(...args: unknown[]): Promise<unknown>;
  discardPaths(...args: unknown[]): Promise<unknown>;
  stageHunks(...args: unknown[]): Promise<unknown>;
  unstageHunks(...args: unknown[]): Promise<unknown>;
  getIdentity(...args: unknown[]): Promise<unknown>;
  setIdentity(...args: unknown[]): Promise<unknown>;
  commitChanges(...args: unknown[]): Promise<unknown>;
  previewCommitAction(...args: unknown[]): Promise<unknown>;
  rebaseOntoCommit(...args: unknown[]): Promise<unknown>;
  cherryPick(...args: unknown[]): Promise<unknown>;
  getStashList(...args: unknown[]): Promise<unknown>;
  stash(...args: unknown[]): Promise<unknown>;
  stashPop(...args: unknown[]): Promise<unknown>;
  stashApply(...args: unknown[]): Promise<unknown>;
  stashDrop(...args: unknown[]): Promise<unknown>;
  getRemotes(...args: unknown[]): Promise<unknown>;
  getReflog(...args: unknown[]): Promise<unknown>;
  getWorktrees(...args: unknown[]): Promise<unknown>;
  createWorktree(...args: unknown[]): Promise<unknown>;
  createManagedWorktree(...args: unknown[]): Promise<unknown>;
  openWorktree(...args: unknown[]): Promise<unknown>;
  lockWorktree(...args: unknown[]): Promise<unknown>;
  unlockWorktree(...args: unknown[]): Promise<unknown>;
  removeWorktree(...args: unknown[]): Promise<unknown>;
  getAgentSettings(...args: unknown[]): Promise<unknown>;
  chooseAgentWorktreeRoot(...args: unknown[]): Promise<unknown>;
  setAgentConcurrency(...args: unknown[]): Promise<unknown>;
  setAgentSessionsEnabled(...args: unknown[]): Promise<unknown>;
  detectAgentAdapters(...args: unknown[]): Promise<unknown>;
  setEnabledAgentAdapters(...args: unknown[]): Promise<unknown>;
  getAiSettings(...args: unknown[]): Promise<unknown>;
  setAiSettings(...args: unknown[]): Promise<unknown>;
  setAiKey(...args: unknown[]): Promise<unknown>;
  clearAiKey(...args: unknown[]): Promise<unknown>;
  testAiConnection(...args: unknown[]): Promise<unknown>;
  generateCommitMessage(...args: unknown[]): Promise<unknown>;
  explainChanges(...args: unknown[]): Promise<unknown>;
  explainConflict(...args: unknown[]): Promise<unknown>;
  explainCommit(...args: unknown[]): Promise<unknown>;
  searchHistory(...args: unknown[]): Promise<unknown>;
  explainLines(...args: unknown[]): Promise<unknown>;
  generatePrDescription(...args: unknown[]): Promise<unknown>;
  getStagedDiff(...args: unknown[]): Promise<unknown>;
  getBlame(...args: unknown[]): Promise<unknown>;
  getUnstagedDiff(...args: unknown[]): Promise<unknown>;
  listAgentTasks(...args: unknown[]): Promise<unknown>;
  createAgentTask(...args: unknown[]): Promise<unknown>;
  createAgentTaskForWorktree(...args: unknown[]): Promise<unknown>;
  stopAgentTask(...args: unknown[]): Promise<unknown>;
  resumeAgentTask(...args: unknown[]): Promise<unknown>;
  archiveAgentTask(...args: unknown[]): Promise<unknown>;
  writeAgentTerminal(...args: unknown[]): Promise<unknown>;
  resizeAgentTerminal(...args: unknown[]): Promise<unknown>;
  acknowledgeAgentAttention(...args: unknown[]): Promise<unknown>;
  onAgentTaskChanged(callback: (payload: unknown) => void): () => void;
  onAgentTerminalData(callback: (payload: unknown) => void): () => void;
  onAgentAttention(callback: (payload: unknown) => void): () => void;
  onAgentQueueChanged(callback: (payload: unknown) => void): () => void;
  getSubmodules(...args: unknown[]): Promise<unknown>;
  initSubmodules(...args: unknown[]): Promise<unknown>;
  updateSubmodules(...args: unknown[]): Promise<unknown>;
  addRemote(...args: unknown[]): Promise<unknown>;
  renameRemote(...args: unknown[]): Promise<unknown>;
  setRemoteUrl(...args: unknown[]): Promise<unknown>;
  removeRemote(...args: unknown[]): Promise<unknown>;
  getFileTree(...args: unknown[]): Promise<unknown>;
  restoreFileFromCommit(...args: unknown[]): Promise<unknown>;
  getTags(...args: unknown[]): Promise<unknown>;
  createTag(...args: unknown[]): Promise<unknown>;
  deleteTag(...args: unknown[]): Promise<unknown>;
  pushTags(...args: unknown[]): Promise<unknown>;
  deleteRemoteTag(...args: unknown[]): Promise<unknown>;
  getTagsAtCommit(...args: unknown[]): Promise<unknown>;
  getOperationState(...args: unknown[]): Promise<unknown>;
  previewMerge(...args: unknown[]): Promise<unknown>;
  parseConflictBlocks(...args: unknown[]): Promise<unknown>;
  readConflict(...args: unknown[]): Promise<unknown>;
  resolveConflict(...args: unknown[]): Promise<unknown>;
  continueOperation(...args: unknown[]): Promise<unknown>;
  abortOperation(...args: unknown[]): Promise<unknown>;
  skipOperation(...args: unknown[]): Promise<unknown>;
  openPullRequest(...args: unknown[]): Promise<unknown>;
  getProviderStatus(...args: unknown[]): Promise<unknown>;
  loginProvider(...args: unknown[]): Promise<unknown>;
  cancelProviderLogin(...args: unknown[]): Promise<unknown>;
  logoutProvider(...args: unknown[]): Promise<unknown>;
  resetHostingVault(...args: unknown[]): Promise<unknown>;
  setPat(...args: unknown[]): Promise<unknown>;
  onProviderState(callback: (payload: unknown) => void): () => void;
  getPullRequests(...args: unknown[]): Promise<unknown>;
  createPullRequest(...args: unknown[]): Promise<unknown>;
  getPullRequestDetail(...args: unknown[]): Promise<unknown>;
  getPullRequestDiff(...args: unknown[]): Promise<unknown>;
  saveReviewDraft(...args: unknown[]): Promise<unknown>;
  submitReview(...args: unknown[]): Promise<unknown>;
  resolveReviewThread(...args: unknown[]): Promise<unknown>;
  checkoutPullRequestSource(...args: unknown[]): Promise<unknown>;
  openReviewInBrowser(...args: unknown[]): Promise<unknown>;
  selectDirectory(...args: unknown[]): Promise<unknown>;
  getRepos(...args: unknown[]): Promise<unknown>;
  addRepo(...args: unknown[]): Promise<unknown>;
  addRepos(...args: unknown[]): Promise<unknown>;
  startRepositoryScan(...args: unknown[]): Promise<unknown>;
  cancelRepositoryScan(...args: unknown[]): Promise<unknown>;
  onRepositoryScanProgress(callback: (payload: unknown) => void): () => void;
  onRepositoryScanComplete(callback: (payload: unknown) => void): () => void;
  removeRepo(...args: unknown[]): Promise<unknown>;
  setActiveRepo(...args: unknown[]): Promise<unknown>;
  getActiveRepo(...args: unknown[]): Promise<unknown>;
  checkIsGitRepo(...args: unknown[]): Promise<unknown>;
  cloneRepository(...args: unknown[]): Promise<unknown>;
  onOperationLog(callback: (payload: unknown) => void): () => void;
  openExternal(...args: unknown[]): Promise<unknown>;
  openTerminal(...args: unknown[]): Promise<unknown>;
  openExplorer(...args: unknown[]): Promise<unknown>;
  getAppVersion(...args: unknown[]): Promise<unknown>;
  getGitVersion(...args: unknown[]): Promise<unknown>;
  exportDiagnostics(...args: unknown[]): Promise<unknown>;
  openInspectorWindow(...args: unknown[]): Promise<unknown>;
  updateInspectorWindow(...args: unknown[]): Promise<unknown>;
  onInspectorClosed(callback: (payload: unknown) => void): () => void;
  onDeepLinkOpen(callback: (payload: unknown) => void): () => void;
  onInspectorRender(callback: (payload: unknown) => void): () => void;
}

/**
 * The inspector window bridge (window.gitTree inside inspector-window.html).
 * Exposes only push subscriptions; no invoke surface by design (ADR-0002).
 */
export interface GitTreeInspectorBridge {
  onInspectorRender(callback: (payload: unknown) => void): () => void;
  onInspectorClosed(callback: () => void): () => void;
}
